config/routes.rb
Rails.application.routes.draw do
  resources :goals
  get 'dashboard/index'
  resources :selections
  mount LetterOpenerWeb::Engine, at: "/letter_opener" if Rails.env.development?
 

  devise_for :users
  resources :authors
  resources :books
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  
  get 'search', :to => "search#index"

  # Defines the root path route ("/")
  root "books#index"
end

app/controllers/book_selections_controller.rb
class BookSelectionsController < ApplicationController
  before_action :set_book_selection, only: %i[ show edit update destroy ]

  # GET /book_selections or /book_selections.json
  def index
    @book_selections = BookSelection.all
  end

  # GET /book_selections/1 or /book_selections/1.json
  def show
  end

  # GET /book_selections/new
  def new
    @book_selection = BookSelection.new
  end

  # GET /book_selections/1/edit
  def edit
  end

  # POST /book_selections or /book_selections.json
  def create
    @book_selection = BookSelection.new(book_selection_params)

    respond_to do |format|
      if @book_selection.save
        format.html { redirect_to book_selection_url(@book_selection), notice: "Book selection was successfully created." }
        format.json { render :show, status: :created, location: @book_selection }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @book_selection.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /book_selections/1 or /book_selections/1.json
  def update
    respond_to do |format|
      if @book_selection.update(book_selection_params)
        format.html { redirect_to book_selection_url(@book_selection), notice: "Book selection was successfully updated." }
        format.json { render :show, status: :ok, location: @book_selection }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @book_selection.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /book_selections/1 or /book_selections/1.json
  def destroy
    @book_selection.destroy

    respond_to do |format|
      format.html { redirect_to book_selections_url, notice: "Book selection was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_book_selection
      @book_selection = BookSelection.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def book_selection_params
      params.require(:book_selection).permit(:add_book, :book_id, :user_id)
    end
end

app/helpers/book_selections_helper.rb
module BookSelectionsHelper
end

app/views/book_selections/_book_selection.html.erb
<div id="<%= dom_id book_selection %>">
  <p>
    <strong>Add book:</strong>
    <%= book_selection.add_book %>
  </p>

  <p>
    <strong>Book:</strong>
    <%= book_selection.book_id %>
  </p>

  <p>
    <strong>User:</strong>
    <%= book_selection.user_id %>
  </p>

</div>

app/views/book_selections/_form.html.erb
<%= simple_form_for(@book_selection) do |f| %>
  <%= f.error_notification %>
  <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>

  <div class="form-inputs">
    <%= f.input :add_book %>
    <%= f.association :book %>
    <%= f.association :user %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/book_selections/edit.html.erb
<h1>Editing book selection</h1>

<%= render "form", book_selection: @book_selection %>

<br>

<div>
  <%= link_to "Show this book selection", @book_selection %> |
  <%= link_to "Back to book selections", book_selections_path %>
</div>

app/views/book_selections/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Book selections</h1>

<div id="book_selections">
  <% @book_selections.each do |book_selection| %>
    <%= render book_selection %>
    <p>
      <%= link_to "Show this book selection", book_selection %>
    </p>
  <% end %>
</div>

<%= link_to "New book selection", new_book_selection_path %>

app/views/book_selections/new.html.erb
<h1>New book selection</h1>

<%= render "form", book_selection: @book_selection %>

<br>

<div>
  <%= link_to "Back to book selections", book_selections_path %>
</div>

app/views/book_selections/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @book_selection %>

<div>
  <%= link_to "Edit this book selection", edit_book_selection_path(@book_selection) %> |
  <%= link_to "Back to book selections", book_selections_path %>

  <%= button_to "Destroy this book selection", @book_selection, method: :delete %>
</div>