config/routes.rb
Rails.application.routes.draw do
  resources :goals
  get 'dashboard/index'
  resources :selections
  mount LetterOpenerWeb::Engine, at: "/letter_opener" if Rails.env.development?
 

  devise_for :users
  resources :authors
  resources :books
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  
  get 'search', :to => "search#index"

  # Defines the root path route ("/")
  root "books#index"
end

app/models/selection.rb
class Selection < ApplicationRecord
  belongs_to :book
  belongs_to :user


  def rating_view 
    if rating == 5
     "5 stars"
    elsif rating == 4
      "4 stars"
    elsif rating == 3
      "3 stars"
    elsif rating == 2
      "2 stars"
    elsif rating == 1
      "1 star"
    else
      "Not rated yet!"
    end
  end 

end

app/controllers/selections_controller.rb
class SelectionsController < ApplicationController
  before_action :set_selection, only: %i[ show edit update destroy ]

  # GET /selections or /selections.json
  def index
    @selections = current_user.selections
  end

  # GET /selections/1 or /selections/1.json
  def show
  end

  # GET /selections/new
  def new
    @selection = Selection.new
  end

  # GET /selections/1/edit
  def edit
  end

  # POST /selections or /selections.json
  def create
    @selection = Selection.new(selection_params)
    @selection.user = current_user

    respond_to do |format|
      if @selection.save
        format.html { redirect_to selection_url(@selection), notice: "Selection was successfully created." }
        format.json { render :show, status: :created, location: @selection }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @selection.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /selections/1 or /selections/1.json
  def update
    respond_to do |format|
      if @selection.update(selection_params)
        format.html { redirect_to selection_url(@selection), notice: "Selection was successfully updated." }
        format.json { render :show, status: :ok, location: @selection }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @selection.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /selections/1 or /selections/1.json
  def destroy
    @selection.destroy

    respond_to do |format|
      format.html { redirect_to selections_url, notice: "Selection was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_selection
      @selection = Selection.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def selection_params
      params.require(:selection).permit(:add_book, :book_id, :user_id, :rating, :status)
    end
end

app/helpers/selections_helper.rb
module SelectionsHelper
end

app/views/selections/_form.html.erb
<%= simple_form_for(@selection) do |f| %>
  <%= f.error_notification %>
  <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>

  <div class="form-inputs">
    <%= f.association :book %>
    <%= f.select :rating, [['Not Read Yet!', 0],['1 Star', 1], ['2 Stars', 2], ['3 Stars', 3], ['4 Stars', 4], ['5 Stars', 5]], {}, {class: "form-control"} %>
    <%= f.select :status, ['Want to read', 'Currently reading', 'Read'], {:selected => 'Want to read'}, {class: "form-control mt-3"}  %>
  </div>

  <div class="form-actions">
    <%= f.button :submit, :class => "btn btn-info mt-3" %>
  </div>
<% end %>

app/views/selections/_selection.html.erb
<div id="<%= dom_id selection %>">

  <p>
    <strong>Book:</strong>
    <%= selection.book.title %>
  </p>

  <p>
    <strong>Author:</strong>
    <%= selection.book.author.full_name %>
  </p>

  <p>
    <strong>Rating:</strong>
      <%= selection.rating_view %>
  </p>
  
  <p>
    <strong>Status:</strong>
    <% if selection.status? %>
      <%= selection.status %>
    <% else %>
      Status Not Set!
    <% end %>
  </p>

</div>

app/views/selections/edit.html.erb
<h1>Editing selection</h1>

<%= render "form", selection: @selection %>

<br>

<div>
  <%= link_to "Show this selection", @selection %> |
  <%= link_to "Back to selections", selections_path %>
</div>

app/views/selections/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Your Books</h1>

<div id="selections">
  <% @selections.each do |selection| %>
    <div class="card">
      <%= render selection %>
      <p>
      <%= button_to "Show Selection", selection, :class => "btn btn-warning", :method => "get" %>
      </p>
    </div>
  <% end %>
</div>

<%= button_to "New selection", new_selection_path, :class => "btn btn-info", :method => "get" %>

app/views/selections/new.html.erb
<h1>New selection</h1>

<%= render "form", selection: @selection %>

<br>

<div>
  <%= link_to "Back to selections", selections_path %>
</div>

app/views/selections/show.html.erb
<p style="color: green"><%= notice %></p>

<div class="card">
  <%= render @selection %>

  <div class="show-button">
    <%= button_to "Edit Book", edit_selection_path(@selection), :class => "btn btn-info mx-3", :method => "get" %>
    <%= button_to "Back to selections", selections_path, :class => "btn btn-warning mx-3", :method => "get" %>

    <%= button_to "Delete Book", @selection, :class => "btn btn-danger mx-3", method: :delete %>
  </div>
</div>