config/routes.rb
Rails.application.routes.draw do
  resources :goals
  get 'dashboard/index'
  resources :selections
  mount LetterOpenerWeb::Engine, at: "/letter_opener" if Rails.env.development?
 

  devise_for :users
  resources :authors
  resources :books
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  
  get 'search', :to => "search#index"

  # Defines the root path route ("/")
  root "books#index"
end

app/models/goal.rb
class Goal < ApplicationRecord
end

app/controllers/goals_controller.rb
class GoalsController < ApplicationController
  before_action :set_goal, only: %i[ show edit update destroy ]

  # GET /goals or /goals.json
  def index
    @goals = Goal.all
  end

  # GET /goals/1 or /goals/1.json
  def show
  end

  # GET /goals/new
  def new
    @goal = Goal.new
  end

  # GET /goals/1/edit
  def edit
  end

  # POST /goals or /goals.json
  def create
    @goal = Goal.new(goal_params)

    respond_to do |format|
      if @goal.save
        format.html { redirect_to goal_url(@goal), notice: "Goal was successfully created." }
        format.json { render :show, status: :created, location: @goal }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @goal.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /goals/1 or /goals/1.json
  def update
    respond_to do |format|
      if @goal.update(goal_params)
        format.html { redirect_to goal_url(@goal), notice: "Goal was successfully updated." }
        format.json { render :show, status: :ok, location: @goal }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @goal.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /goals/1 or /goals/1.json
  def destroy
    @goal.destroy

    respond_to do |format|
      format.html { redirect_to goals_url, notice: "Goal was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_goal
      @goal = Goal.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def goal_params
      params.require(:goal).permit(:number_of_books, :read_by)
    end
end

app/helpers/goals_helper.rb
module GoalsHelper
end

app/views/goals/_form.html.erb
<%= simple_form_for(@goal) do |f| %>
  <%= f.error_notification %>
  <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>

  <div class="form-inputs">
    <%= f.input :number_of_books %>
    <%= f.input :read_by %>
  </div>

  <div class="form-actions">
    <%= f.button :submit, :class => "btn btn-warning", :method => "get" %>
  </div>
<% end %>

app/views/goals/_goal.html.erb
<div id="<%= dom_id goal %>">
  <p>
    <strong>Number of books:</strong>
    <%= goal.number_of_books %>
  </p>

  <p>
    <strong>Read by:</strong>
    <%= goal.read_by %>
  </p>

</div>

app/views/goals/edit.html.erb
<h1>Editing goal</h1>

<%= render "form", goal: @goal %>

<br>

<div>
  <%= link_to "Show this goal", @goal %> |
  <%= link_to "Back to goals", goals_path %>
</div>

app/views/goals/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Goals</h1>

<div id="goals">
  <% @goals.each do |goal| %>
    <div class="card">
      <%= render goal %>
      <p>
      <%= button_to "Show this goal", goal, :class => "btn btn-info", :method => "get" %>
      </p>
    </div>
  <% end %>
</div>

<%= button_to "New goal", new_goal_path, :class => "btn btn-warning", :method => "get" %>

app/views/goals/new.html.erb
<h1>New goal</h1>

<%= render "form", goal: @goal %>

<br>

<div>
  <%= link_to "Back to goals", goals_path %>
</div>

app/views/goals/show.html.erb
<p style="color: green"><%= notice %></p>

<div class="card">
  <%= render @goal %>

  <div class="show-button">
    <%= button_to "Edit this goal", edit_goal_path(@goal), :class => "btn btn-info", :method => "get" %>
    <%= button_to "Back to goals", goals_path, :class => "btn btn-warning mx-3", :method => "get" %>

    <%= button_to "Destroy this goal", @goal, :class => "btn btn-danger",  method: :delete %>
  </div>